- name: populate static files
  shell: source /var/opt/wsgi/mbl-data/env_secrets && /var/opt/wsgi/mbl-data/env/bin/python manage.py collectstatic --no-input
  args:
    chdir: /var/opt/wsgi/mbl-data/mbl-data
  become: yes
  become_user: mbl-data
- name: migrate database
  shell: source /var/opt/wsgi/mbl-data/env_secrets && /var/opt/wsgi/mbl-data/env/bin/python manage.py migrate
  args:
    chdir: /var/opt/wsgi/mbl-data/mbl-data
  become: yes
  become_user: mbl-data
- name: create superuser in mbl-data
  shell: source /var/opt/wsgi/mbl-data/env_secrets && echo "from django.contrib.auth.models import User; User.objects.filter(email='{{ django_admin_email}}').delete(); User.objects.create_superuser('{{ django_admin_user }}', '{{ django_admin_email }}', '{{ django_admin_password }}')" | /var/opt/wsgi/mbl-data/env/bin/python manage.py shell
  args:
    chdir: /var/opt/wsgi/mbl-data/mbl-data
  become: yes
  become_user: mbl-data
  no_log: true
